#!groovy
package it.com.cloudogu.ces.cesbuildlib.Sh
import static groovy.test.GroovyAssert.*

node {

    def cesBuildLib = libraryFromLocalRepo().com.cloudogu.ces.cesbuildlib

    def sh = cesBuildLib.Sh.new(this)

    echo pwd()
    def folderContents = sh.returnStdOut('ls -la')
    assertTrue('ls does not return ..', folderContents.contains('..'))
    assertTrue('ls does not return Jenkinsfile', folderContents.contains('Jenkinsfile'))
}

def libraryFromLocalRepo() {
    // Workaround for loading the current repo as shared build lib.
    // Checks out to workspace local it named like the identifier.
    // We have to pass an identifier with version (which is ignored). Otherwise the build fails.
    library(identifier: 'ces-build-lib@snapshot', retriever: legacySCM(scm))
}